### ISSUE TITLE
getting \u0000 instead of mac address in wyzesense.json

### ISSUE THREAD

**Issue by biga888** [kevinvincent/ha-wyzesense#100]
I have been getting NULL mac address in the JSON file which seems to be messing things up. 
["\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"]

I try and add other sensors and before I used to get real mac addresses, but now they just add with no mac and I just get the single Null address.

Running Hassio 0.104.3 in a Virtual Box on a CentOS 7 server

Log files with debug
https://pastebin.com/BhEawC3T

**Comment by biga888** [comment]
ok, it looks like thee entities are stuck in the HA database. trying to remove, but it seems to be having issues through the GUI. I will see if I can remove manually ?

**Comment by biga888** [comment]
ok, I cleaned everything out and now wyze just keeps returning a found sensor with a blank mac address. Going to uninstall and etc to see if that clears things up

**Comment by biga888** [comment]
ok, I cleaned everything out and I get nothing now after a scan. Detects the sensor, but the mac is returned blank and the json file is not created.
https://pastebin.com/PxedSnvF

**Comment by biga888** [comment]
ok, I decided to plug my bridge back into a camera and find that my sensors are not connecting. Motion ones are ok, but the contact ones are having an issue. I am going to contact Wyze support as it seems that others have had similar issues. Seems like a hardware issue.

**Comment by azehnwirth** [comment]
Several other 'null MAC address' issues posted on this github repo seem to have been caused by one or more of the sensor devices having an almost dead battery. It seems to happen suddenly despite other battery level indicators looking fine until they begin failing. The first sign of a dead/dying battery for WyzeSense sensors integrated in Home Assistant with this this plugin is that "all was going well, now everything is failing to load and I keep seeing the devices recognised with weird null MAC addresses."

The question is, which sensor is it causing the grief? Keep reading, I've seen the answers in the resolved issues section of the repo. 👍

**Comment by biga888** [comment]
THANK YOU!!!!

I found I only had one good battery out of the 4 door sensors, so just
ordered more form Amazon.
They went quick, guess the battery levels are not accurate.

I also noticed that I was getting about 5 quicker flashes, so that must be
a dead battery indicator.

Thank you, I was banging my head trying to figure this out.

Cheers
