### ISSUE TITLE
Include in HACS default repository

### ISSUE THREAD

**Issue by Royal2000H** [kevinvincent/ha-wyzesense#12]
As you recommend using HACS for installation, you may want to consider adding your project to show up under their defaults.

https://custom-components.github.io/hacs/developer/include_default_repositories/

**Comment by kevinvincent** [comment]
I believe the correct way to do this is to transfer this repository to https://github.com/custom-components

However, the end goal is to get this into HASS core. Because of that, I'm holding off on it. The plan is to let this sit for 1 more release cycle to iron out any issues and then target inclusion in HA 0.99

**Comment by Royal2000H** [comment]
I think there's two ways to include. The way you linked is likely the legacy way to include. I think now they're steering that you can include your repository so that you don't have to copy code into their repository. You can even see commits doing the method I linked.

That said, great news that you're aiming to get into HASS core. Exciting news.

**Comment by kevinvincent** [comment]
Ah okay I didn't realize that was the correct way now. Thank you!
