### ISSUE TITLE
BinarySensorDevice is deprecated (HA core .110)

### ISSUE THREAD

**Issue by swingerman** [kevinvincent/ha-wyzesense#139]
It seems that the new version of HA core (.110) introduced some breaking changes and the wyzesense component is affected:

`BinarySensorDevice is deprecated, modify WyzeSensor to extend BinarySensorEntity`

**Comment by mgriffin13** [comment]
As I was talking about in https://github.com/kevinvincent/ha-wyzesense/issues/111, this component should really be redesigned to be a top-level integration, rather than only a binary_sensor platform. That would fix this deprecation, plus it would bring Wyze up to be more in line with the other integrations that exist.

**Comment by tteck** [comment]
Replace BinarySensorDevice with BinarySensorEntity in two places, line 23 and 185 in the binary_sensor.py.

**Comment by photinus** [comment]
Will have an updated release out here in the next day or so. The fix is already committed to master.
