### ISSUE TITLE
'wyzesense.scan' no longer working

### ISSUE THREAD

**Issue by rappo** [kevinvincent/ha-wyzesense#169]
I'm currently running Home Assistant 0.114.4 via Docker (Unraid)

I initially setup ha-wyzesense ~2 weeks ago. Setup and scan were flawless. All paired sensors are still working as expected. 

If I wyzesense.scan now I get the following error with nothing else relevant in the log:
> ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.22609200354640] Error handling message: expected dict for dictionary value @ data['service_data']. Got 'wyzesense.scan'

May not be related, but this first happened after updating to 0.114.3. Updated to .4 and tried again with the same outcome.

Any ideas?

btw- fantastic work on this! I'm impressed with how easy the setup was and how fast the local control is. I'll definitely be getting more sensors (as soon as I can add them again...)

**Comment by va3dprinter** [comment]
Nooooo... same thing just happened to me. I had *just* gotten another 12 sensors configured and made the mistake of upgrading and now nothing works and the service can't be called. Incompatibility between the WyzeSense code and HA? The whole setup between Wyze and HA seems tenuous. Any reason it can't be as clean as the other integrations?

**Comment by rappo** [comment]
@va3dprinter nothing at all works for you? That's different than my situation. My existing paired sensors are working fine, even after updates and container restarts. The only thing not working, that I know of, is scan / adding new devices (admittedly, I haven't tried remove).

**Comment by va3dprinter** [comment]
No, nothing's working after the upgrade to .4. I'm not sure how to peak under the hood either to see if some other service needs to be started. It's only the Wyze devices that are affected and I'd love to try to troubleshoot but not sure where to start with the container. I welcome ideas...

**Comment by va3dprinter** [comment]
...it's like the underlying Wyze service isn't starting. Before the upgrade, when I'd restart HA, it would take a minute or so (running on a Pi4w/4gb). Now when I reboot the server, HA comes up pretty quick but none of the Wyze components are available. I'm wondering if the boot-time difference is HA not checking/looking for the ~20+ Wyze devices. The Wyze dongle is flashing blue/yellow. I've tried unplugging/plugging the dongle to see if something needed to be reset there. Is there someplace under the hood that I can check to see if something isn't running that should be?

**Comment by va3dprinter** [comment]
...not to beat a dead horse but I found the problem. When setting up the Wyze portion in the configuration.yaml, I had explicitly stated the device name as /dev/hidraw2. Looking at the home-assistant.log you could see that it couldn't find that device after the upgrade. I changed it to 'auto' as I'd seen on other setup configurations and things all came back after a reboot. The log does still throw a warning stating "WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant." I understand the concept of the community integrations and I'd love to see this one go mainstream since they seem to be some of the best performing, best priced sensors.

**Comment by rappo** [comment]
so... it's working for me, and the solution is quite embarrassing/simple.

I was putting 'wyzesense.scan' in the Service Data section of the front end, which was passing invalid parameters. I guess I had tried simply selecting the service and it didn't add my device (and there's no feedback in the UI that the service was called...), so I have been mistakenly putting the service in the service data section. The error message from HA wasn't very helpful, either

![image](https://user-images.githubusercontent.com/2245234/91664568-f68a0d00-eaa4-11ea-9afb-7ffde2a75f7c.png)
