### ISSUE TITLE
Wyze bridge does not mount as /dev/hidraw* in hassio

### ISSUE THREAD

**Issue by hanssep** [kevinvincent/ha-wyzesense#4]
Trying to get this to work on hassio installed on an debian vm.

While the Wyze bridge seems to be recognized as a USB device in the home-assistant docker, it does not show up as an available device in /dev.

Output of `find /sys/bus/usb/devices/usb*/ -name dev` in the docker environment shows
```
/sys/bus/usb/devices/usb1/dev
/sys/bus/usb/devices/usb2/2-1/dev
/sys/bus/usb/devices/usb2/2-1/2-1:1.0/0003:1A86:E024.0001/hidraw/hidraw0/dev
/sys/bus/usb/devices/usb2/2-1/2-1:1.0/usbmisc/hiddev0/dev
/sys/bus/usb/devices/usb2/dev
/sys/bus/usb/devices/usb3/dev
/sys/bus/usb/devices/usb4/dev
/sys/bus/usb/devices/usb5/dev
```

`dmesg` in the docker environment shows
```
[  693.196091] usb 2-1: new full-speed USB device number 2 using uhci_hcd
[  693.608136] usb 2-1: New USB device found, idVendor=1a86, idProduct=e024
[  693.608139] usb 2-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[  693.619012] hidraw: raw HID events driver (C) Jiri Kosina
[  693.624633] usbcore: registered new interface driver usbhid
[  693.624635] usbhid: USB HID core driver
[  693.627866] hid-generic 0003:1A86:E024.0001: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:1d.0-1/input0
```

Maybe I'm missing something or does hassio not support this awesome custom module?

**Comment by mediacowboy** [comment]
It should be the hidraw0.

/sys/bus/usb/devices/usb2/2-1/2-1:1.0/0003:1A86:E024.0001/hidraw/hidraw0/dev

**Comment by kevinvincent** [comment]
Sorry, I’ve been traveling for a few days. Is your home assistant docker container in privileged mode?

Also as @mediacowboy mentioned above make sure you’re using hidraw0 instead of hiddev.

Also just for information are you running latest home assistant? I’ve had reports that maybe the move to an alpine Linux based container might be causing issues

**Comment by hanssep** [comment]
Thanks Kevin. Issue is with our hassio environment. Growing tired with hassio so did a new home-assistant install in docker container so I have a lot more control. Initially got a completely different error but that turned out to be the USB extension cable I was using. Had to plug/unplug a few times but then it worked! Thanks for all the hard work! This is going to be awesome assuming Wyze doesn’t sabotage this!

--
Hans

**Comment by kevinvincent** [comment]
Ah okay, I'm glad it was just an environment-specific issue. In order to help other people can you clarify what your solution was?

Was your old setup hassio (latest version?). And then did you move to just plain home assistant? What OS is it on now?

**Comment by kevinvincent** [comment]
If you have the information above I'd still appreciate it! Closing this out. 

Feel free to submit another issue if you run into anything else. Also please update your component, I released a change yesterday that adds retrying for simple failures at startup. Seems like it's mainly pi users that were running into that but it could be helpful at some point.

**Comment by hanssep** [comment]
Thanks Kevin. I've been able to "fix" this by moving away from HASSIO to a standard HA docker container. 

My HASSIO environment: HASSIO installed on Debian VM running in proxmox. USB bridge enabled and seen by Debian. When testing with the base Python script in Debian, Wyze bridge is recognized as /dev/hidraw0 and sensors are seen. When checking the same in the HASSIO container Wyze bridge is not seen as a device in /dev and thus Wyze HACS integration fails due to device not found.

My HA docker environment: simple HA container on a Debian VM running in proxmox with docker-compose device setting to passthrough /dev/hidraw0 (something I could not figure out how to do with HASSIO). Had to unplug and replug Wyze bridge but after that worked as expected.

The ability to control exactly how the HA docker container is configured made me decide to move away from HASSIO. Sure, I'll miss some conviences like updates and some HASSIO addons but nothing that cannot be replaced with a simple docker-compose setup, portainer and watchtower.

**Comment by Wheaties466** [comment]
I just started having this issue when I upgraded my hassio host. It does not recognize the wyze bridge even on the host system.

**Comment by VarenDerpsAround** [comment]
> I just started having this issue when I upgraded my hassio host. It does not recognize the wyze bridge even on the host system.

I'm not sure where to begin?

This issue is almost a year old. The hidraw issues have been around 150% as long. Consider that the issues you're having have been discussed in various closed issue tickets, and has been added to the installation guide seen [here](https://github.com/kevinvincent/ha-wyzesense) scrolls down a ways, read it entirely, follow the directions for enabling logs and see which particular issue you're having. 

don't comment on 11 month old **closed** issue tickets, I'm fairly sure I might be one of 3 people to be following this entire repo. I get emails for days, I reply to comments such as yours because I care about wyze, and my smart home.

Please, upvote the wyze integration on the wyze forums if you could, thanks.

**[https://forums.wyzecam.com/t/home-assistant-integration/3971 - upvote this please, this repo owner no longer has time to maintain this, and we're struggling to keep up](https://forums.wyzecam.com/t/home-assistant-integration/3971)**

**Comment by Wheaties466** [comment]
Thank you for the response. I’ll increase my logging. I’m just not sure that is going to help since the device is not being seen as a hidraw device on the host os . I’ll do some more digging to get more info. Thank you for helping
